### ISSUE TITLE
gsub regular expression failure

### ISSUE THREAD

**Issue by msg** [moonjit/moonjit#105] opened 2020-03-18 13:45 UTC
`print(string.format('<%s>', (' one two '):gsub('^%s*', '')))`

prints:

`< one two >`

luajit-2.1 and lua5.1 both print:

`<one two >`

As expected

**Comment by siddhesh** [comment] 2020-03-21 04:41
Is this with moonjit 2.1.x or 2.2?  2.2 is not meant to be compatible with luajit-2.1.

**Comment by msg** [comment] 2020-03-21 11:43
2.2.   I'm not sure compatibility is at issue here.  I would expect that
regular expression to
work in any version.  I guess if it doesn't, a document describing how it
works would be
necessary.  I looked at the release notes for 2.2 and there is nothing
about regular expression
changes.

I also ran the same test on lua 5.3.5 and it works.

Matt

**Comment by mcepl** [comment] 2020-03-30 11:03
According to @erw7 this is what breaks building of neovim in openSUSE, https://github.com/neovim/neovim/issues/12058

**Comment by erw7** [comment] 2020-03-30 11:34
In master, this problem seems to have been fixed by https://github.com/moonjit/moonjit/commit/cabe3b3cbddc1d3657af451ab0ed82416117cbc7.

**Comment by siddhesh** [comment] 2020-03-30 15:36
Thanks for digging this out @erw7. Closed as duplicate of #86 .

**Closed as completed by siddhesh** 2020-03-30 15:36 UTC
