### ISSUE TITLE
math_special test from luajit2-test-suite fails on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [moonjit/moonjit#2] opened 2019-09-11 06:41 UTC
Hi,

The test fails with the following error
/usr/local//bin/luajit-2.1.0-beta3: math_special.lua:44: got: "+1 +0 nan nan +1 +1 nan nan nan"
expected: "+1 +1 +1 +1 +1 +1 +1 +1 +1"
stack traceback:
        [C]: in function 'error'
        math_special.lua:25: in function 'check'
        math_special.lua:44: in main chunk
        [C]: at 0x10005940
Failed test when running /usr/local//bin/luajit-2.1.0-beta3 math_special.lua 1: 256
1 tests failed.

The test passes on x86_64.

It is in the test/unportable folder and the only other test in this folder is ffi_arith_int64.lua and is skipped on Power.

Thanks,
Priya

**Comment by seth-priya** [comment] 2019-09-11 09:25
Looks like there are no obvious issues with the test case, it is ultimately boiling down to the differences in the following values in Intel and Power, which I cross checked directly on the luajit2 shell (as well as placing appropriate print statements in the test file) on the two platforms and compared the output
```
		Intel   Power
x	y	x^y 	x^y
0       0       1	1
-0      0       1	0
0.5     0       1	nan
-0.5    0       1	nan
1       0       1	1
-1      0       1	1
inf     0       1	nan
-inf    0       1	nan
nan     0       1	nan
```
In the test case, this is the code in question
```
     42 for j=1,#inp do
     43   local y = inp[j]
     44   check(function(x) return x^y end, powcheck[j])
     45 end
```

where inp is
```
      2 local inp = { 0, -"0", 0.5, -0.5, 1, -1, 1/0, -1/0, 0/0 }
```

and expected output is
```
     31 local powcheck = {
     32   "+1 +1 +1 +1 +1 +1 +1 +1 +1",
```

while actual is 
```
"+1 +0 nan nan +1 +1 nan nan nan"
```

Is this difference expected is the question...

**Comment by siddhesh** [comment] 2019-09-16 01:50
That looks like a bug; pow(anything, 0) should be 1.  I'll see if I can find a ppc64le machine to test this, possibly next weekend since I'm still travelling.  If you or anybody would like to take a dig at this, please reduce the test to a minimal reproducer that returns nan for x^0.  Once the reproducer is available, one could pore over the BC_POW implementation to try and figure out what's wrong.

**Comment by seth-priya** [comment] 2019-09-16 10:30
@siddhesh thanks a lot for the pointer. 

So, as I understand the implementation for BC_POW for Power is in src/vm_ppc.dasc which is low level assembly stuff, something that I don't have a lot of expertise on. BUT, I tried looking at the code and was comparing the implementation from the original PR at
https://github.com/LuaJIT/LuaJIT/pull/140/
with the current (re-based) implementation in this repository and one change I could not understand completely was
https://github.com/LuaJIT/LuaJIT/blob/2bf1b24e251eb24c4196ec81d75edb1f214faf04/src/vm_ppc.dasc#L3989
TO
https://github.com/siddhesh/LuaJIT/blob/master/src/vm_ppc.dasc#L4541

I tried changing the BASE to BASE_HI in the above line and that seems to make the test pass, I printed the actual and expected values via the test case, just to be sure and this is what I get ..

got: "+0 -0 +0.5 -0.5 +1 -1 +inf -inf nan"
expected: "+0 -0 +0.5 -0.5 +1 -1 +inf -inf nan"
got: "+1 +1 +1 +1 +1 +1 +1 +1 +1"
expected: "+1 +1 +1 +1 +1 +1 +1 +1 +1"
got: "+1 +1 +1 +1 +1 +1 +1 +1 +1"
expected: "+1 +1 +1 +1 +1 +1 +1 +1 +1"
got: "+0 +0 +0.70711 nan +1 nan +inf +inf nan"
expected: "+0 +0 +0.70711 nan +1 nan +inf +inf nan"
got: "+inf +inf +1.4142 nan +1 nan +0 +0 nan"
expected: "+inf +inf +1.4142 nan +1 nan +0 +0 nan"
got: "+0 -0 +0.5 -0.5 +1 -1 +inf -inf nan"
expected: "+0 -0 +0.5 -0.5 +1 -1 +inf -inf nan"
got: "+inf -inf +2 -2 +1 -1 +0 -0 nan"
expected: "+inf -inf +2 -2 +1 -1 +0 -0 nan"
got: "+0 +0 +0 +0 +1 +1 +inf +inf nan"
expected: "+0 +0 +0 +0 +1 +1 +inf +inf nan"
got: "+inf +inf +inf +inf +1 +1 +0 +0 nan"
expected: "+inf +inf +inf +inf +1 +1 +0 +0 nan"
got: "nan nan nan nan +1 nan nan nan nan"
expected: "nan nan nan nan +1 nan nan nan nan"
got: "+0 +0 +0.5 +0.5 +1 +1 +inf +inf nan"
expected: "+0 +0 +0.5 +0.5 +1 +1 +inf +inf nan"
got: "+0 +0 +0 -1 +1 -1 +inf -inf nan"
expected: "+0 +0 +0 -1 +1 -1 +inf -inf nan", "+0 -0 +0 -1 +1 -1 +inf -inf nan"
got: "+0 +0 +1 +0 +1 -1 +inf -inf nan"
expected: "+0 +0 +1 +0 +1 -1 +inf -inf nan", "+0 -0 +1 -0 +1 -1 +inf -inf nan"
got: "+0 -0 +0.70711 nan +1 nan +inf nan nan"
expected: "+0 -0 +0.70711 nan +1 nan +inf nan nan"
got: "+0 -0 +0.47943 -0.47943 +0.84147 -0.84147 nan nan nan"
expected: "+0 -0 +0.47943 -0.47943 +0.84147 -0.84147 nan nan nan"
got: "+1 +1 +0.87758 +0.87758 +0.5403 +0.5403 nan nan nan"
expected: "+1 +1 +0.87758 +0.87758 +0.5403 +0.5403 nan nan nan"
got: "+0 -0 +0.5463 -0.5463 +1.5574 -1.5574 nan nan nan"
expected: "+0 -0 +0.5463 -0.5463 +1.5574 -1.5574 nan nan nan"
got: "+0 -0 +0.5236 -0.5236 +1.5708 -1.5708 nan nan nan"
expected: "+0 -0 +0.5236 -0.5236 +1.5708 -1.5708 nan nan nan"
got: "+1.5708 +1.5708 +1.0472 +2.0944 +0 +3.1416 nan nan nan"
expected: "+1.5708 +1.5708 +1.0472 +2.0944 +0 +3.1416 nan nan nan"
got: "+0 -0 +0.46365 -0.46365 +0.7854 -0.7854 +1.5708 -1.5708 nan"
expected: "+0 -0 +0.46365 -0.46365 +0.7854 -0.7854 +1.5708 -1.5708 nan"
got: "-inf -inf -0.69315 nan +0 nan +inf nan nan"
expected: "-inf -inf -0.69315 nan +0 nan +inf nan nan"
got: "-inf -inf -0.30103 nan +0 nan +inf nan nan"
expected: "-inf -inf -0.30103 nan +0 nan +inf nan nan"
got: "+1 +1 +1.6487 +0.60653 +2.7183 +0.36788 +inf +0 nan"
expected: "+1 +1 +1.6487 +0.60653 +2.7183 +0.36788 +inf +0 nan

**Comment by seth-priya** [comment] 2019-09-16 10:33
Played around with some additional values on the luajit shell, focusing on the pow() operation and found the output to be as expected.

**Comment by siddhesh** [comment] 2019-09-16 20:44
Nice catch!  Please make a PR to fix this up and I'll merge it.

**Comment by siddhesh** [comment] 2019-09-24 12:12
Fixed with the following commits:

https://github.com/siddhesh/LuaJIT/commit/d83ef2b043f0a63903f9b44f81822b1e585e189b
https://github.com/siddhesh/LuaJIT/commit/1022c08bbc0101eb4227191f304ce9c74150ade5

Thank you!

**Closed as completed by siddhesh** 2019-09-24 12:12 UTC
